#!/usr/bin/env bash

TMP_DIR=/tmp/licpro-php-slides

echo -e '\e[32m→ Stashing modified/untracked files\e[0m'
git stash -u

echo -e '\e[32m→ Building slides\e[0m'
make build

echo -e '\e[32m→ Preparing publication\e[0m'
rm -rf $TMP_DIR
mkdir $TMP_DIR
mv iut-php.html $TMP_DIR/index.html
mv iut-extended.html $TMP_DIR/extended.html
cp -R themes/ $TMP_DIR

echo -e '\e[32m→ Switching back to gh-pages\e[0m'
git checkout gh-pages

mv $TMP_DIR/* .
git add *.html themes/avalanche/avalanche/
git commit -m "Publish slides (`date`)"

echo -e '\e[32m→ Pushing\e[0m'
git push origin gh-pages -f

git clean -fdx

echo -e '\e[32m→ Switching back to master\e[0m'
git checkout master

git stash apply
