#!/usr/bin/env bash

TMP_DIR=/tmp/licpro-php-slides

git stash -u

make build

rm -rf $TMP_DIR
mkdir $TMP_DIR
mv iut-php.html $TMP_DIR/index.html
mv iut-extended.html $TMP_DIR/extended.html
cp -R themes/ $TMP_DIR

git checkout gh-pages

mv $TMP_DIR/* .
git add *.html themes/avalanche/avalanche/
git commit -m "Publish slides (`date`)"

git push origin gh-pages -f

git clean -fdx

git checkout master

git stash apply
